import "./globals.css";
import "@repo/ui/globals.css";
import { cn } from "@ui/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={cn("dark font-sans", fontSans.variable)}>
        {children}
      </body>
    </html>
  );
}
